services:
    server:
        build: ./src/Lwt/
        ports:
          - "5000:80"
        container_name: server
        links:
          - mysql:mysql
          - japanese-segmenter:japanese-segmenter
        depends_on:
          - mysql
        restart: always
        environment:
          - 'LWTDB=Server=mysql;Database=lwt;User=root;'
    mysql:
      image: mysql/mysql-server:8.0.28-1.2.7-server
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ${LWT_MYSQL_DIR}:/var/lib/mysql
      ports:
        - "3306:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: '%'
    japanese-segmenter:
      build: ./JapaneseSegmenter/Natto
      ports:
        - "63825:8080"
      restart: always
      container_name: japanese-segmenter

