// <auto-generated />
using LWT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LWT.Migrations
{
    [DbContext(typeof(LWTContext))]
    partial class LWTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("LWT.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TextSize");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("LWT.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LWT.Models.Term", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int?>("LanguageID");

                    b.Property<int>("Level");

                    b.Property<string>("Meaning");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("LWT.Models.Text", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioURL");

                    b.Property<string>("Content");

                    b.Property<int?>("LanguageID");

                    b.Property<string>("SourceURL");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("LWT.Models.Term", b =>
                {
                    b.HasOne("LWT.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID");
                });

            modelBuilder.Entity("LWT.Models.Text", b =>
                {
                    b.HasOne("LWT.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID");
                });
#pragma warning restore 612, 618
        }
    }
}
