version: "3"
services:
    server:
        build: .
        ports:
          - "5000:80"
        container_name: server
        links:
          - mongo
        depends_on:
          - mongo
        restart: always
    mongo:
        image: mongo
        restart: always
        container_name: mongo
        ports:
          - "27017:27017"
        volumes:
          - /data/db:/data/db
