version: "3"
services:
    server:
        build: .
        ports:
          - "5000:80"
        container_name: server
        links:
          - mysql:mysql
        depends_on:
          - mysql
        restart: always
        environment:
          - 'LWTDB=Server=mysql;Database=lwt;User=root;'
    mysql:
      image: mysql/mysql-server
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_HOST: '%'
