version: "3"
services:
    server:
        build: .
        ports:
          - "5000:80"
        container_name: server
        links:
          - mysql:mysql
        depends_on:
          - mysql
        restart: always
        environment:
          LWTDB: "Server=mysql;Database=lwt;User=root;Password=;"
    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ''
