// <autogenerated/>

namespace Lwt
{
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;

    /// <summary>
    /// a.
    /// </summary>
    public class Program
    {
        /// <summary>
        /// a.
        /// </summary>
        /// <param name="args"></param>
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        /// <summary>
        /// a.
        /// </summary>
        /// <param name="args">args.</param>
        /// <returns>asd.</returns>
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
}
