// <autogenerated/>


using App.Metrics.AspNetCore;
using App.Metrics.Formatters.Prometheus;

namespace Lwt;

using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;

/// <summary>
/// Application.
/// </summary>
public static class Program
{
    /// <summary>
    /// application entry point.
    /// </summary>
    /// <param name="args"></param>
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    /// <summary>
    /// create the web host builder.
    /// </summary>
    /// <param name="args">arguments.</param>
    /// <returns></returns>
    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseMetricsWebTracking()
            .UseMetrics(options =>
            {
                options.EndpointOptions = o =>
                {
                    o.MetricsTextEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter();
                    o.MetricsEndpointOutputFormatter = new MetricsPrometheusProtobufOutputFormatter();
                    o.EnvironmentInfoEndpointEnabled = true;
                };
            })
            .UseStartup<Startup>();
}